# Generated by Django 4.2.7 on 2025-07-27 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("funny", "Funny"),
                            ("poetic", "Poetic"),
                            ("minimal", "Minimal"),
                            ("trendy", "Trendy"),
                        ],
                        default="trendy",
                        max_length=10,
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "people",
                    models.CharField(
                        blank=True, help_text="Who's in the photo?", max_length=200
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Where was this taken?", max_length=200
                    ),
                ),
                (
                    "moment",
                    models.TextField(
                        blank=True, help_text="Special moment to highlight"
                    ),
                ),
                (
                    "sample_captions",
                    models.TextField(
                        blank=True,
                        help_text="Your favorite captions for style reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SongSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title_artist", models.CharField(max_length=200)),
                ("order", models.IntegerField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="captions.captionrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedCaption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption_text", models.TextField()),
                ("reason", models.TextField()),
                ("order", models.IntegerField()),
                ("has_bias_warning", models.BooleanField(default=False)),
                ("bias_terms", models.JSONField(default=list)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="captions.captionrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_name", models.CharField(max_length=100)),
                ("explanation", models.TextField()),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter",
                        to="captions.captionrequest",
                    ),
                ),
            ],
        ),
    ]
